syntax on
color zanders
se ts=4
se sw=4
se ls=2
se et
se ai
se ru

" disable parenthesis highlighting
let loaded_matchparen = 1

" jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

au! BufRead,BufNewFile *.json set filetype=json
au! BufRead,BufNewFile *.jake,Jakefile set filetype=jake
au! BufRead,BufNewFile *.ejs set filetype=html

" file specific
au! Filetype javascript,json,jake setlocal syntax=javascript ts=2 sw=2
au! Filetype ruby setlocal ts=2 sw=2

